[game]
hostname = "☢️S.T.A.L.K.E.R. [EN Test] [PvP Arena] ☣️"
desc = "Server in S.T.A.L.K.E.R. setting. Now in English! This is a PvP deathmatch arena gamemode."
#map = "STWorld" # st-changes-dev-map
map_pool = "STDefaultMapPool"  # st-changes-map-pool
defaultpreset = "STDAGamePreset" # STDA: changed default
maxplayers = 45
soft_max_players = 30
map_rotation = false
role_timers = true
peaceful_end = false
# lobbyduration = 10
contraband_examine = false
role_whitelist = false
maxcharacterslots = 1

[shuttle]
auto_call_time = 0
emergency = false
arrivals = false
preload_grids = false
camera_rotation_locked = true

[ic]
flavor_text = true
punctuation = false

[tts]
enabled = false

[hub]
advertise = true
tags = "lang:en,rp:high,region:us_e"
hub_urls = "https://hub.spacestation14.com/"

[crewmanifest]
no_entity = false
